### ISSUE TITLE
Selector suggestion:

### ISSUE THREAD

**Issue by himedlooff** [STRML/strml.net#1]
Fun site! I wanted to point out an inconsistency with the following selectors:

```css
#work-text .md h1,h2,h3,h4,h5,h6 {
  ...
}

#work-text .md h1,h2,h3,h4,h5,h6,ul,p {
  ...
}
```

It looks like the intention is to style elements within `#work-text .md` but that's only happening for the first selector `#work-text .md h1`... `h2,h3,h4,h5,h6,ul,p` will select those elements across the entire page, not just within `#work-text .md`.

I think what you're looking for is:

```css
.md h1, .md h2, .md h3, .md h4, .md h5, .md h6 {
  ...
}

.md h1, .md h2, .md h3, .md h4, .md h5, .md h6, .md ul, .md p {
  ...
}
```

I ditched `#work-text` from all of those so you could style markdown in any container.

**Comment by STRML** [comment]
Thanks!
