### ISSUE TITLE
This is how to return a responsibility? I don't have changed anything.

### ISSUE THREAD

**Issue by rayliao** [STRML/strml.net#3]
`npm install`
`npm run dev`
![qq20150602-1 2x](https://cloud.githubusercontent.com/assets/5601068/7939192/4553fd84-097c-11e5-99b5-eca5de86948f.png)
Seem don't support the async.

**Comment by STRML** [comment]
Looks like babel isn't being invoked properly. Make sure your dependencies are all up to date. I've pushed an update that upgrades the minimum versions.

**Comment by rayliao** [comment]
babel-core version: 5.4.7
babel-loader version: 5.1.3

**Comment by STRML** [comment]
Do you have a global babelrc? That might be causing the problem, overriding the .babelrc in the directory.

Try changing L19 of `webpack-dev-server.config.js` to `          loader: 'babel-loader?stage=1'`

**Comment by rayliao** [comment]
It works! Thank you.

BTW, When I run out `npm run dev`, `webpack: bundle is now VALID.` 
The dist folder no app. js and browsers do not open the page.

**Comment by STRML** [comment]
Yes, there's no app.js. I don't have anything that automatically opens up the page (although that's easy to do), you just have to go to http://localhost:4003/index-dev.html

**Comment by rayliao** [comment]
`Uncaught ReferenceError: regeneratorRuntime is not defined` L40 app.js

**Comment by STRML** [comment]
Very strange. It appears the babelrc is not registering at all. One sec.

**Comment by STRML** [comment]
Ok @rayliao pull latest and give it a shot.
